name: super_dates
description: "A minimal typesafe DateTime API extension for Dart."
version: 0.0.1
homepage: https://github.com/superlistapp/super_dates
repository: https://github.com/superlistapp/super_dates
issue_tracker: https://github.com/superlistapp/super_dates/issues

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
